apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gt1xd3skg-nodejs
  janus-idp.io/tekton: gt1xd3skg-nodejs
  backstage.io/kubernetes-id: gt1xd3skg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gt1xd3skg-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
