apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gt1xd3skg-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gt1xd3skg-nodejs 
  name: gt1xd3skg-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: gt1xd3skg-nodejs 
